#:kivy 1.0

#:import ConfigScreen dronebuilder.components.config.ConfigScreen

<ConfigScreen>:
    name: "config"
    MDBoxLayout:
        orientation: "vertical"

        MDLabel:
            id: filepath
            text: "CONFIG"
            font_color: "black"
            font_size: 40
            pos_hint: {"center_x": 0.5, "center_y": 0.5}

        MDFillRoundFlatButton:
            text: "Hello"
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            on_release:

